// OAuth layer for context-kernel MCP server.
//
// Implements single-user OAuth via @cloudflare/workers-oauth-provider v0.8.1 so that
// claude.ai's connector UI (which requires OAuth) can use context-kernel without
// breaking the existing plain-bearer flow for Claude Code CLI.
//
// Architecture:
//  1. External token resolution (resolveExternalToken): validates existing plain-bearer
//     READ_TOKEN and WRITE_TOKEN, mapping them to OAuth tokens with read-only scope.
//     This preserves backward compatibility: existing plain-bearer clients keep working.
//  2. DCR (Dynamic Client Registration): accepts claude.ai's self-registration with
//     minimal validation (redirect_uri whitelist only).
//  3. /authorize: the library only reports this URL in its metadata — it does NOT
//     implement the endpoint itself. We render a one-field login form (owner's
//     READ_TOKEN) here and gate completeAuthorization() on it, since without that
//     check anyone who reaches /authorize would mint themselves a valid read-scope
//     access token with no credential at all.
//  4. MCP scope isolation: all OAuth-issued tokens grant only "read" scope (get_context,
//     list_sections, get_meta). Plain-bearer tokens retain their original read/write split.

import { OAuthProvider, getOAuthApi } from "@cloudflare/workers-oauth-provider";
import type {
  ResolveExternalTokenInput,
  ResolveExternalTokenResult,
  ClientRegistrationCallbackOptions,
  ClientRegistrationCallbackResult,
  OAuthProviderOptions,
} from "@cloudflare/workers-oauth-provider";
import { scopesForToken } from "./auth.js";
import type { Env } from "../types.js";

/**
 * Configure the OAuth provider with resolveExternalToken to accept existing
 * plain-bearer tokens (READ_TOKEN, WRITE_TOKEN) and map them to OAuth-issued
 * read-scope tokens. This callback is invoked when a token is presented but
 * not found in OAUTH_KV, giving us a chance to validate legacy tokens.
 *
 * Plain-bearer tokens are treated as read-only at the OAuth level (mapped to
 * "read" scope in the token props), even if they were originally WRITE_TOKEN.
 * This is intentional: OAuth clients cannot escalate to write scope; only
 * direct plain-bearer WRITE_TOKEN (for local/trusted servers) grants write.
 */
async function resolveExternalToken(
  input: ResolveExternalTokenInput,
): Promise<ResolveExternalTokenResult | null> {
  const env = input.env as Env;
  const scopes = await scopesForToken(input.token, env);

  // Token is not valid (matches neither READ_TOKEN nor WRITE_TOKEN).
  if (scopes.size === 0) {
    return null;
  }

  // Token is valid. Map it to OAuth props with read scope only.
  // This ensures OAuth-layered access (including claude.ai via OAuth flow)
  // never gets write access, even if backed by a WRITE_TOKEN. Write access
  // stays reserved for direct plain-bearer WRITE_TOKEN (local servers only).
  return {
    props: {
      // "read" scope: access to read tools only (get_context, list_sections, get_meta).
      // Even plain-bearer WRITE_TOKEN becomes read-scoped at the OAuth level.
      scope: ["read"],
      // Audit: mark as "legacy plain-bearer token mapped to OAuth".
      source: "plain_bearer_token",
      originalScopes: Array.from(scopes),
    },
  };
}

/**
 * DCR callback: accept registration requests (RFC 7591) from claude.ai.
 * Minimal validation: only restrict redirect_uri to HTTPS and a whitelist.
 * The clientId / clientSecret are auto-generated by the library.
 */
async function clientRegistrationCallback(
  options: ClientRegistrationCallbackOptions,
): Promise<ClientRegistrationCallbackResult | void> {
  const metadata = options.clientMetadata;

  // Require redirect_uri(s).
  if (!("redirect_uris" in metadata) || !Array.isArray(metadata.redirect_uris)) {
    return {
      code: "invalid_client_metadata",
      description: "redirect_uris is required and must be an array.",
      status: 400,
    };
  }

  // Validate each redirect_uri.
  for (const uri of metadata.redirect_uris as unknown[]) {
    if (typeof uri !== "string") {
      return {
        code: "invalid_client_metadata",
        description: "redirect_uris must contain only strings.",
        status: 400,
      };
    }

    // Only allow HTTPS (and localhost for dev).
    const url = new URL(uri);
    if (url.protocol !== "https:" && url.hostname !== "localhost") {
      return {
        code: "invalid_client_metadata",
        description: `redirect_uri must use HTTPS (or localhost for dev): ${uri}`,
        status: 400,
      };
    }
  }

  // Allow registration. The library auto-generates clientId and clientSecret.
  // Return void/undefined to accept.
}

/**
 * Build the OAuthProviderOptions shared by both the OAuthProvider instance
 * (which handles /token, /register, /.well-known/*) and getOAuthApi (which
 * we use in handleAuthorize to parse/complete the auth request for the
 * /authorize endpoint the library expects *us* to implement).
 */
function buildProviderOptions(
  env: Env,
  apiHandler: Required<Pick<ExportedHandler<Env>, "fetch">>,
  defaultHandler: ExportedHandler<Env>,
  requestUrl: URL,
): OAuthProviderOptions<Env> {
  // Dynamically extract base URL from request to support any deployed domain.
  // Falls back to a generic localhost URL for dev if origin is unset.
  const baseUrl = requestUrl.origin || "http://localhost:8787";
  const baseUrlWithSlash = baseUrl.endsWith("/") ? baseUrl : baseUrl + "/";

  return {
    // /mcp is an API route: the library validates the presented token
    // (its own issued token, or a plain-bearer token via
    // resolveExternalToken below) before invoking apiHandler with the
    // resolved scope in ctx.props. Unauthenticated /mcp requests and all
    // other paths fall through to defaultHandler.
    apiRoute: "/mcp",
    apiHandler,
    defaultHandler,

    // OAuth server metadata endpoints and token endpoint.
    authorizeEndpoint: baseUrlWithSlash + "authorize",
    tokenEndpoint: baseUrlWithSlash + "token",
    clientRegistrationEndpoint: baseUrlWithSlash + "register",

    // Token lifetime: 1 hour for access, 30 days for refresh (library defaults).
    // Scopes available to this server: only "read" (write is not exposed).
    scopesSupported: ["read"],

    // Callback: validate tokens that are not in OAUTH_KV.
    // This is where we accept plain-bearer READ_TOKEN / WRITE_TOKEN and treat them
    // as read-scoped OAuth tokens for backward compatibility.
    resolveExternalToken,

    // Callback: handle dynamic client registration (DCR).
    // claude.ai will use this to register itself.
    clientRegistrationCallback,

    // Protected resource metadata (RFC 9728): describe this as an MCP server.
    resourceMetadata: {
      resource: baseUrlWithSlash + "mcp",
      resource_name: "context-kernel MCP Server",
      bearer_methods_supported: ["header"],
      scopes_supported: ["read"],
    },
  };
}

/**
 * Build and return an OAuthProvider instance configured for this MCP server.
 * Handles /token, /register, /.well-known/* internally, validates /mcp
 * (apiRoute), and falls through to defaultHandler for everything else —
 * including /authorize, which handleAuthorize (below) implements.
 */
export function createOAuthProvider(
  env: Env,
  apiHandler: Required<Pick<ExportedHandler<Env>, "fetch">>,
  defaultHandler: ExportedHandler<Env>,
  requestUrl: URL,
): OAuthProvider<Env> {
  return new OAuthProvider(buildProviderOptions(env, apiHandler, defaultHandler, requestUrl));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderLoginForm(actionUrl: string, error?: string): Response {
  const errorHtml = error
    ? `<p style="color:#b00;margin:0 0 1rem">${escapeHtml(error)}</p>`
    : "";
  const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>context-kernel</title></head>
<body style="font-family:system-ui,sans-serif;max-width:28rem;margin:4rem auto;padding:0 1rem">
  <h1 style="font-size:1.1rem">Authorize access to context-kernel</h1>
  <p>Enter your READ_TOKEN to grant this client read-only access to your curated context.</p>
  ${errorHtml}
  <form method="POST" action="${escapeHtml(actionUrl)}">
    <input type="password" name="token" placeholder="READ_TOKEN" autofocus
      style="width:100%;padding:.5rem;box-sizing:border-box;margin-bottom:.75rem">
    <button type="submit" style="padding:.5rem 1rem">Authorize</button>
  </form>
</body></html>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=UTF-8" },
  });
}

/**
 * Implements the /authorize endpoint the library's metadata points at but
 * does not itself serve. Single-user login: the owner's plain-bearer
 * READ_TOKEN doubles as the OAuth login credential. GET renders the form;
 * POST verifies the submitted token (constant-time, via scopesForToken) and,
 * only on a match, completes the authorization and redirects back to the
 * client with an authorization code. No token, no grant — this is what
 * closes the "anyone can DCR + hit /authorize and mint a token" hole.
 */
export async function handleAuthorize(
  request: Request,
  env: Env,
  apiHandler: Required<Pick<ExportedHandler<Env>, "fetch">>,
  defaultHandler: ExportedHandler<Env>,
  requestUrl: URL,
): Promise<Response> {
  const options = buildProviderOptions(env, apiHandler, defaultHandler, requestUrl);
  const helpers = getOAuthApi(options, env);

  // The submitted form action carries the original OAuth query params, so
  // parseAuthRequest (which reads from the URL) works for GET and POST alike.
  const authRequest = await helpers.parseAuthRequest(request);

  if (request.method === "GET") {
    return renderLoginForm(requestUrl.pathname + requestUrl.search);
  }

  if (request.method === "POST") {
    const form = await request.formData();
    const submittedToken = form.get("token");
    const scopes =
      typeof submittedToken === "string"
        ? await scopesForToken(submittedToken, env)
        : new Set<string>();

    if (!scopes.has("read")) {
      return renderLoginForm(requestUrl.pathname + requestUrl.search, "Invalid token.");
    }

    const { redirectTo } = await helpers.completeAuthorization({
      request: authRequest,
      userId: "owner",
      metadata: { source: "context-kernel-login" },
      scope: ["read"],
      props: {
        scope: ["read"],
        source: "oauth_login",
      },
    });

    return new Response(null, { status: 302, headers: { Location: redirectTo } });
  }

  return new Response("Method not allowed", { status: 405 });
}

/**
 * Check if a request URL path is an OAuth endpoint (not MCP).
 * Returns true for paths like /.well-known/*, /authorize, /token, /register.
 */
export function isOAuthPath(url: URL): boolean {
  const path = url.pathname;
  return (
    path.startsWith("/.well-known/") ||
    path === "/authorize" ||
    path === "/token" ||
    path === "/register"
  );
}
