// OAuth layer for context-kernel MCP server.
//
// Implements single-user OAuth via @cloudflare/workers-oauth-provider v0.8.1 so that
// claude.ai's connector UI (which requires OAuth) can use context-kernel without
// breaking the existing plain-bearer flow for Claude Code CLI.
//
// Architecture:
//  1. External token resolution (resolveExternalToken): validates existing plain-bearer
//     READ_TOKEN and WRITE_TOKEN, mapping them to OAuth tokens with read-only scope.
//     This preserves backward compatibility: existing plain-bearer clients keep working.
//  2. DCR (Dynamic Client Registration): accepts claude.ai's self-registration with
//     minimal validation (redirect_uri whitelist only).
//  3. OAuth endpoints (/.well-known/oauth-authorization-server, /authorize, /token, etc.)
//     are routed through OAuthProvider alongside the existing /mcp MCP endpoint.
//  4. MCP scope isolation: all OAuth-issued tokens grant only "read" scope (get_context,
//     list_sections, get_meta). Plain-bearer tokens retain their original read/write split.

import { OAuthProvider } from "@cloudflare/workers-oauth-provider";
import type {
  ResolveExternalTokenInput,
  ResolveExternalTokenResult,
  ClientRegistrationCallbackOptions,
  ClientRegistrationCallbackResult,
} from "@cloudflare/workers-oauth-provider";
import { scopesForToken } from "./auth.js";
import type { Env } from "../types.js";

/**
 * Configure the OAuth provider with resolveExternalToken to accept existing
 * plain-bearer tokens (READ_TOKEN, WRITE_TOKEN) and map them to OAuth-issued
 * read-scope tokens. This callback is invoked when a token is presented but
 * not found in OAUTH_KV, giving us a chance to validate legacy tokens.
 *
 * Plain-bearer tokens are treated as read-only at the OAuth level (mapped to
 * "read" scope in the token props), even if they were originally WRITE_TOKEN.
 * This is intentional: OAuth clients cannot escalate to write scope; only
 * direct plain-bearer WRITE_TOKEN (for local/trusted servers) grants write.
 */
async function resolveExternalToken(
  input: ResolveExternalTokenInput,
): Promise<ResolveExternalTokenResult | null> {
  const env = input.env as Env;
  const scopes = await scopesForToken(input.token, env);

  // Token is not valid (matches neither READ_TOKEN nor WRITE_TOKEN).
  if (scopes.size === 0) {
    return null;
  }

  // Token is valid. Map it to OAuth props with read scope only.
  // This ensures OAuth-layered access (including claude.ai via OAuth flow)
  // never gets write access, even if backed by a WRITE_TOKEN. Write access
  // stays reserved for direct plain-bearer WRITE_TOKEN (local servers only).
  return {
    props: {
      // "read" scope: access to read tools only (get_context, list_sections, get_meta).
      // Even plain-bearer WRITE_TOKEN becomes read-scoped at the OAuth level.
      scope: ["read"],
      // Audit: mark as "legacy plain-bearer token mapped to OAuth".
      source: "plain_bearer_token",
      originalScopes: Array.from(scopes),
    },
  };
}

/**
 * DCR callback: accept registration requests (RFC 7591) from claude.ai.
 * Minimal validation: only restrict redirect_uri to HTTPS and a whitelist.
 * The clientId / clientSecret are auto-generated by the library.
 */
async function clientRegistrationCallback(
  options: ClientRegistrationCallbackOptions,
): Promise<ClientRegistrationCallbackResult | void> {
  const metadata = options.clientMetadata;

  // Require redirect_uri(s).
  if (!("redirect_uris" in metadata) || !Array.isArray(metadata.redirect_uris)) {
    return {
      code: "invalid_client_metadata",
      description: "redirect_uris is required and must be an array.",
      status: 400,
    };
  }

  // Validate each redirect_uri.
  for (const uri of metadata.redirect_uris as unknown[]) {
    if (typeof uri !== "string") {
      return {
        code: "invalid_client_metadata",
        description: "redirect_uris must contain only strings.",
        status: 400,
      };
    }

    // Only allow HTTPS (and localhost for dev).
    const url = new URL(uri);
    if (url.protocol !== "https:" && url.hostname !== "localhost") {
      return {
        code: "invalid_client_metadata",
        description: `redirect_uri must use HTTPS (or localhost for dev): ${uri}`,
        status: 400,
      };
    }
  }

  // Allow registration. The library auto-generates clientId and clientSecret.
  // Return void/undefined to accept.
}

/**
 * Build and return an OAuthProvider instance configured for this MCP server.
 * This provider:
 *  - Accepts OAuth authorization code flow
 *  - Accepts plain-bearer token validation via resolveExternalToken
 *  - Implements DCR for claude.ai registration
 *  - Stores all state in OAUTH_KV
 *  - Issues access tokens with "read" scope only
 *
 * The provider is configured with defaultHandler that accepts the MCP handler.
 * When a request comes in, the OAuthProvider:
 *  - Routes OAuth paths (/.well-known/*, /authorize, /token, /register) internally
 *  - Delegates all other requests (including /mcp) to defaultHandler (the MCP handler)
 */
export function createOAuthProvider(
  env: Env,
  defaultHandler: ExportedHandler<Env>,
): OAuthProvider<Env> {
  const baseUrl = new URL("https://context-kernel.dkritarth.workers.dev");

  return new OAuthProvider({
    // OAuth server metadata endpoints and token endpoint.
    authorizeEndpoint: baseUrl + "authorize",
    tokenEndpoint: baseUrl + "token",
    clientRegistrationEndpoint: baseUrl + "register",

    // Token lifetime: 1 hour for access, 30 days for refresh (library defaults).
    // Scopes available to this server: only "read" (write is not exposed).
    scopesSupported: ["read"],

    // Default handler: the MCP handler. The OAuthProvider delegates non-OAuth
    // requests (including /mcp) to this handler, which performs plain-bearer
    // token validation as before.
    defaultHandler,

    // Callback: validate tokens that are not in OAUTH_KV.
    // This is where we accept plain-bearer READ_TOKEN / WRITE_TOKEN and treat them
    // as read-scoped OAuth tokens for backward compatibility.
    resolveExternalToken,

    // Callback: handle dynamic client registration (DCR).
    // claude.ai will use this to register itself.
    clientRegistrationCallback,

    // Protected resource metadata (RFC 9728): describe this as an MCP server.
    resourceMetadata: {
      resource: baseUrl + "mcp",
      resource_name: "context-kernel MCP Server",
      bearer_methods_supported: ["header"],
      scopes_supported: ["read"],
    },
  });
}

/**
 * Check if a request URL path is an OAuth endpoint (not MCP).
 * Returns true for paths like /.well-known/*, /authorize, /token, /register.
 */
export function isOAuthPath(url: URL): boolean {
  const path = url.pathname;
  return (
    path.startsWith("/.well-known/") ||
    path === "/authorize" ||
    path === "/token" ||
    path === "/register"
  );
}
